- name: Install ".exe" + Update
  hosts: ADApp
  tags: AfterAD
  vars_files: ./vars.yml
  gather_facts: false
  tasks:
  - name: Touch a file (creates if not present, updates modification time if present)
    ansible.windows.win_file:
      path: "{{ item }}"
      state: directory
    loop: "{{ Path }}"
  - name: autorisation chocolatey install
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

  - name: Install Chocolatey
    win_chocolatey:
      name: chocolatey
      state: present
  - name: Set the Chocolatey Cache location
    win_chocolatey_config:
      name: cacheLocation
      state: present
      value: "{{ Path[1] }}"

  - name: Install EXE
    win_chocolatey:
      name: "{{ item }}"
      state: present
    loop: "{{ ChocolateyInstall }}"
  
  - name: Install All Windows Updates
    win_updates:
      category_names: '*'
      reboot: yes