- name: Set Network + AD
  hosts: ADApp
  vars_files: ./vars.yml
  gather_facts: false
  tasks:
  - name: Install ASPnet Core
    chocolatey.chocolatey.win_chocolatey:
      name: aspnetcore-runtimepackagestore
      state: present

  - name: Install IIS Web-Server with management tools
    ansible.windows.win_feature:
      name: Web-Server
      state: present
      include_sub_features: no
      include_management_tools: yes
    register: win_feature

  - name: Reboot if installing Web-Server feature requires it
    ansible.windows.win_reboot:
    when: win_feature.reboot_required

  - name: Config App in IIS
    tags: iisTest
    community.windows.win_iis_website:
      name: "{{ AppSetting.name }}"
      state: started
      port: "{{ AppSetting.port }}"
      physical_path: "{{ AppSetting.path }}"