version: "3.8"
#https://github.com/itzg/docker-minecraft-server
#https://github.com/itzg/docker-mc-backup

services:
  server:
    image: itzg/minecraft-server:2022.14.0
    command: 
      - cp /srv/dev-disk-by-uuid-88861031-30c5-4c7f-9b3f-2f4087d6f927/Raid/Users/Nicolas/Minecraft/icon-server.jpg /srv/dev-disk-by-uuid-9a8441b6-d899-4899-971f-3068a8e9c748/Ssd/Docker/volumes/minecraft_data/_data
    environment:
      EULA: TRUE
      MOTD: "RaBByT // test backup"
      VERSION: 1.18.2
      TYPE: FORGE
      FORGE_VERSION: 40.1.60
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=100"
      MAX_PLAYERS: 3
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 7
      SIMULATION_DISTANCE: 5
      MAX_BUILD_HEIGHT: 512
      ENABLE_WHITELIST: TRUE
      DIFFICULTY: hard
      OPS: "RaBByt_Tv,Zaula,TBMPQF"
      ALLOW_NETHER: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      GENERATE_STRUCTURES: TRUE
      SNOOPER_ENABLED: FALSE
      MAX_TICK_TIME: 60000
      TZ: Europe/Paris
      MODE: survival # 0=survival, 1=creative, 2=adventure, 3=spectator // not sure it work
      FORCE_GAMEMODE: TRUE # force default gamemode at connection
      HARDCORE: FALSE
      ALLOW_FLIGHT: TRUE
      MAX_WORLD_SIZE: 10000000
      SPAWN_ANIMALS: TRUE
      SPAWN_MONSTERS: TRUE
      SPAWN_NPCS: TRUE
      PVP: TRUE
      LEVEL_TYPE: normal # type of generating world
      SERVER_NAME: RaBByT_S1
      #ICON: ./icon-server.jpg
      ENABLE_RCON: TRUE
      RCON_PASSWORD: $RCON_PWD
      RCON_CMDS_STARTUP:  |-
        gamerule keepinventory true
        gamerule playersSleepingPercentage 1
    deploy:
      resources:
        limits:
          memory: 6400M
    volumes:
      - data:/data
      - /srv/dev-disk-by-uuid-88861031-30c5-4c7f-9b3f-2f4087d6f927/Raid/Users/Nicolas/Minecraft/icon-server.jpg:/data/icon-server.jpg
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 25566:25565
      - 25575:25575
    networks:
      - web
  backups:
    image: itzg/mc-backup
    environment:
      TZ: Europe/Paris
      INITIAL_DELAY: 2m
      BACKUP_INTERVAL: 1h
      PRUNE_BACKUPS_DAYS: 14
      RCON_HOST: server
      RCON_PORT: 25575
      RCON_PASSWORD: $RCON_PWD
      DEST_DIR: /backups
      LINK_LATEST: FALSE
      TAR_COMPRESS_METHOD: gzip
      ZSTD_PARAMETERS: -3 --long=25 --single-thread
    volumes:
    - data:/data:ro
    - backup:/backups
    network_mode: "service:server"
    
volumes:
  data: {}
  backup: {}
networks:
    web:
      external: true