version: "3.8"

services:
  Minecraft:
    image: itzg/minecraft-server:2022.14.0
    labels:
      - traefik.enable=true
      - traefik.http.routers.minecraft_mod.rule=Host(`minecraft.laura-et-nicolas.com`)
      - traefik.http.routers.minecraft_mod.entrypoints=web
    container_name: Minecraft_mod
    environment:
      EULA: TRUE
      MOTD: "RaBByT Season v1"
      VERSION: 1.18.2
      TYPE: FORGE
      FORGE_VERSION: 40.1.60
      MEMORY: ""
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=95"
      MAX_PLAYERS: 10 
      SPAWN_PROTECTION: 0 
      VIEW_DISTANCE: 12 
      SIMULATION_DISTANCE: 12
      MAX_BUILD_HEIGHT: 512
      ENABLE_WHITELIST: TRUE
      DIFFICULTY: Hard
      OPS: "RaBByT_Tv"
      ALLOW_NETHER: TRUE
      ANNOUNCE_PLAYER_ACHIEVEMENTS: TRUE
      GENERATE_STRUCTURES: TRUE
      SNOOPER_ENABLED: FALSE
      MAX_TICK_TIME: 60000
      SPAWN_MONSTERS: TRUE
      TZ: Europe/Paris
      ENABLE_RCON: FALSE
      #RCON_CMDS_STARTUP:  |-
      #  gamerule keepinventory true
      #  gamerule playersSleepingPercentage 1
      PROXY: Traefik:25565
    deploy:
      resources:
        limits:
          memory: 13056M
    volumes:
      - Minecraft_mod:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 25565:25565
    networks:
      - web
    
volumes:
  Minecraft_mod:
    external: true
networks:
    web:
      external: true