version: "3.8"

services:
  ansible:
    image: rabbyt/ansible_ubuntu
    restart: "no"
    ports:
      - 5985:5985
    environment:
      TZ: Europe/Paris
    volumes:
      - data:/Ansible-perso
    command: >
      sh -c "git clone https://github.com/Nicolas-mahe/Ansible-perso.git && \
            git config --global --add safe.directory /Ansible-perso && \
            cd ./Ansible-perso/Ansible/ && \
            git pull && \
            ansible-galaxy collection install -r requirement.yml && \
            ansible-playbook -i inventory.yml playbook.yml &&\
            tail -F anything"

volumes:
  data: {}